# Generated by Django 3.2.5 on 2021-08-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinnedlocation',
            name='endDate',
            field=models.DateTimeField(null=True),
        ),
    ]
