# Generated by Django 3.2.5 on 2021-08-26 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_alter_pinnedlocation_enddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinnedlocation',
            name='endDate',
        ),
    ]
