# Generated by Django 3.2.5 on 2021-08-26 15:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapi', '0003_remove_pinnedlocation_enddate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transectionHistory',
            new_name='transactionHistory',
        ),
    ]
